import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { CartDrawer } from "@/components/cart-drawer";
import { CartStoreHydration } from "@/components/cart-store-hydration";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartStoreHydration />
        <CartDrawer />
        {children}
      </body>
    </html>
  );
}
